[project]
name = "call-center-ai"
version = "0.1.0"
description = ""
authors = [
    {name = "yassine zadod",email = "yassine.zadod@e-polytechnique.ma"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi (>=0.136.1,<0.137.0)",
    "uvicorn (>=0.46.0,<0.47.0)",
    "python-multipart (>=0.0.27,<0.0.28)",
    "openai-whisper (>=20250625,<20250626)",
    "motor (>=3.7.1,<4.0.0)",
    "faster-whisper (>=1.2.1,<2.0.0)",
    "groq (>=1.2.0,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "vercel-blob (>=0.4.2,<0.5.0)"
]

[tool.poetry]
packages = [{include = "call_center_ai", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
